/* data.js — база данных протоколов RFC Garden
   Источник истина. PROTOCOLS.json — экспорт той же структуры.
   Обновляйте оба файла синхронно. */
const protocolsData = {
    "protocols": [
        { "id": "rfc0791", "number": 791, "name": "IPv4", "fullName": "Internet Protocol version 4", "year": 1981, "status": "active", "layer": "network", "category": "addressing", "plant": "tree",
          "description": "Основной протокол маршрутизации в интернете. Отвечает за адресацию и фрагментацию пакетов.", "where": "Везде: каждый пакет в интернете", "fact": "Адреса IPv4 закончились ещё в 2011 году — поэтому придумали IPv6 и NAT",
          "dependsOn": [], "usedBy": ["rfc0793","rfc0768","rfc0826","rfc0792","rfc4271","rfc1918","rfc4960"], "replaces": [], "replacedBy": ["rfc8200"], "color": "#4CAF50" },
        { "id": "rfc0792", "number": 792, "name": "ICMP", "fullName": "Internet Control Message Protocol", "year": 1981, "status": "active", "layer": "network", "category": "control", "plant": "sprout",
          "description": "Служебные сообщения сети: ping, ошибки доставки, диагностика. Голос сети, когда что-то идёт не так.", "where": "Команда ping", "fact": "Ping написали за одну ночь в 1983 году",
          "dependsOn": ["rfc0791"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#CDDC39" },
        { "id": "rfc0793", "number": 793, "name": "TCP", "fullName": "Transmission Control Protocol", "year": 1981, "status": "active", "layer": "transport", "category": "transport", "plant": "vine",
          "description": "Надёжный протокол с установкой соединения. Гарантирует доставку и порядок пакетов.", "where": "Сайты, почта, файлы — почти всё", "fact": "Трёхэтапное рукопожатие: SYN → SYN-ACK → ACK",
          "dependsOn": ["rfc0791"], "usedBy": ["rfc2616","rfc5321","rfc0959","rfc8446","rfc4253","rfc6455","rfc1939","rfc3501","rfc4271","rfc0854","rfc1436","rfc1945","rfc3977","rfc4511","rfc5246"], "replaces": [], "replacedBy": [], "color": "#2196F3" },
        { "id": "rfc0768", "number": 768, "name": "UDP", "fullName": "User Datagram Protocol", "year": 1980, "status": "active", "layer": "transport", "category": "transport", "plant": "vine",
          "description": "Протокол без установки соединения. Быстрый, без гарантии доставки. Стриминг, игры, DNS.", "where": "Видео, игры, DNS", "fact": "Без гарантии доставки — зато быстрее всех",
          "dependsOn": ["rfc0791"], "usedBy": ["rfc1035","rfc5905","rfc9000","rfc5766","rfc1157","rfc3261","rfc3550","rfc7252"], "replaces": [], "replacedBy": [], "color": "#9C27B0" },
        { "id": "rfc0826", "number": 826, "name": "ARP", "fullName": "Address Resolution Protocol", "year": 1982, "status": "active", "layer": "link", "category": "addressing", "plant": "mushroom",
          "description": "Находит MAC-адрес устройства по его IP-адресу в локальной сети.", "where": "Локальная сеть, домашний Wi-Fi", "fact": "ARP-таблицу компьютера видно командой arp -a",
          "dependsOn": ["rfc0791"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#795548" },
        { "id": "rfc1035", "number": 1035, "name": "DNS", "fullName": "Domain Name System", "year": 1987, "status": "active", "layer": "application", "category": "naming", "plant": "flower",
          "description": "Система доменных имён: превращает понятные адреса (google.com) в IP-адреса.", "where": "Каждый адрес в браузере", "fact": "Первый домен symbolics.com зарегистрирован в 1985 году",
          "dependsOn": ["rfc0768"], "usedBy": ["rfc8484"], "replaces": [], "replacedBy": [], "color": "#00BCD4" },
        { "id": "rfc5321", "number": 5321, "name": "SMTP", "fullName": "Simple Mail Transfer Protocol", "year": 2008, "status": "active", "layer": "application", "category": "email", "plant": "flower",
          "description": "Передача электронной почты между серверами.", "where": "Отправка писем", "fact": "Первая версия 1982 года слала письма открытым текстом",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": ["rfc2821"], "replacedBy": [], "color": "#E91E63" },
        { "id": "rfc0959", "number": 959, "name": "FTP", "fullName": "File Transfer Protocol", "year": 1985, "status": "legacy", "layer": "application", "category": "file_transfer", "plant": "mushroom",
          "description": "Один из старейших протоколов передачи файлов. Постепенно вытесняется.", "where": "Старые файловые архивы", "fact": "Пароли в FTP летят открытым текстом — поэтому его вытеснили",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#607D8B" },
        { "id": "rfc1939", "number": 1939, "name": "POP3", "fullName": "Post Office Protocol v3", "year": 1996, "status": "active", "layer": "application", "category": "email", "plant": "mushroom",
          "description": "Получение почты с сервера: скачивает письма на устройство и обычно удаляет их там.", "where": "Почтовые программы", "fact": "Обычно удаляет письма с сервера после скачивания",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#8D6E63" },
        { "id": "rfc3501", "number": 3501, "name": "IMAP", "fullName": "Internet Message Access Protocol", "year": 2003, "status": "active", "layer": "application", "category": "email", "plant": "vine",
          "description": "Доступ к почте прямо на сервере: письма синхронизированы между устройствами.", "where": "Почта на телефоне и компьютере сразу", "fact": "Письма хранятся на сервере и синхронизируются",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#009688" },
        { "id": "rfc2131", "number": 2131, "name": "DHCP", "fullName": "Dynamic Host Configuration Protocol", "year": 1997, "status": "updated", "layer": "application", "category": "addressing", "plant": "sprout",
          "description": "Раздаёт устройствам IP-адреса и сетевые настройки автоматически при подключении.", "where": "Подключение к Wi-Fi", "fact": "Именно DHCP выдаёт тебе IP в кафе с ноутбуком",
          "dependsOn": ["rfc0768"], "usedBy": [], "replaces": ["rfc1541"], "replacedBy": [], "color": "#FF7043" },
        { "id": "rfc5905", "number": 5905, "name": "NTP", "fullName": "Network Time Protocol", "year": 2010, "status": "active", "layer": "application", "category": "sync", "plant": "mushroom",
          "description": "Синхронизация часов: держит время точным на миллиардах устройств.", "where": "Часы телефона и компьютера", "fact": "Миллисекундная точность на миллиардах устройств",
          "dependsOn": ["rfc0768"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#FFD54F" },
        { "id": "rfc2616", "number": 2616, "name": "HTTP/1.1", "fullName": "Hypertext Transfer Protocol", "year": 1999, "status": "updated", "layer": "application", "category": "web", "plant": "flower",
          "description": "Протокол гипертекста — основа Всемирной паутины.", "where": "Каждый сайт", "fact": "Методы GET и POST придуманы здесь",
          "dependsOn": ["rfc0793"], "usedBy": ["rfc6455","rfc2617","rfc2818","rfc6749","rfc8484"], "replaces": ["rfc2068","rfc1945"], "replacedBy": ["rfc7540","rfc9114"], "color": "#FF9800" },
        { "id": "rfc7540", "number": 7540, "name": "HTTP/2", "fullName": "Hypertext Transfer Protocol v2", "year": 2015, "status": "active", "layer": "application", "category": "web", "plant": "flower",
          "description": "Мультиплексирование запросов и сжатие заголовков поверх TCP.", "where": "Современные сайты", "fact": "Мультиплексирование: сто запросов в одном соединении",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": ["rfc2616"], "replacedBy": ["rfc9114"], "color": "#FF5722" },
        { "id": "rfc8200", "number": 8200, "name": "IPv6", "fullName": "Internet Protocol version 6", "year": 2017, "status": "active", "layer": "network", "category": "addressing", "plant": "tree",
          "description": "Новое поколение IP: 128-битные адреса — хватит на всё.", "where": "Новые сети, мобильный интернет", "fact": "Адресов хватит на каждую песчинку Земли",
          "dependsOn": [], "usedBy": [], "replaces": ["rfc0791"], "replacedBy": [], "color": "#8BC34A" },
        { "id": "rfc8446", "number": 8446, "name": "TLS 1.3", "fullName": "Transport Layer Security 1.3", "year": 2018, "status": "active", "layer": "presentation", "category": "security", "plant": "tree",
          "description": "Шифрование соединений: замок на двери интернета. HTTPS = HTTP + TLS.", "where": "Замок в адресной строке (HTTPS)", "fact": "Рукопожатие за один round-trip — страницы открываются быстрее",
          "dependsOn": ["rfc0793"], "usedBy": ["rfc9114"], "replaces": ["rfc5246"], "replacedBy": [], "color": "#4DD0E1" },
        { "id": "rfc4253", "number": 4253, "name": "SSH", "fullName": "Secure Shell (SSH) Transport Layer Protocol", "year": 2006, "status": "active", "layer": "application", "category": "security", "plant": "vine",
          "description": "Безопасный удалённый доступ к машинам через шифрованный канал.", "where": "Удалённое управление серверами", "fact": "Придуман в 1995 году после атаки на сеть автора",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#607D8B" },
        { "id": "rfc4271", "number": 4271, "name": "BGP", "fullName": "Border Gateway Protocol 4", "year": 2006, "status": "active", "layer": "network", "category": "routing", "plant": "tree",
          "description": "Протокол маршрутизации между автономными системами. Скелет всего интернета: кто с кем связан.", "where": "Магистрали интернета", "fact": "Ошибка в BGP в 2008 году «уронила» YouTube по всему миру",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#EF6C00" },
        { "id": "rfc6455", "number": 6455, "name": "WebSocket", "fullName": "The WebSocket Protocol", "year": 2011, "status": "active", "layer": "application", "category": "web", "plant": "vine",
          "description": "Двунаправленный канал поверх HTTP: чаты, игры, live-обновления.", "where": "Чаты, онлайн-игры, live-ленты", "fact": "Начинается как HTTP-запрос, а потом становится каналом",
          "dependsOn": ["rfc2616"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#AB47BC" },
        { "id": "rfc9000", "number": 9000, "name": "QUIC", "fullName": "QUIC: A UDP-Based Multiplexed Transport", "year": 2021, "status": "active", "layer": "transport", "category": "transport", "plant": "vine",
          "description": "Новый транспорт от Google: TLS встроен, соединение мгновенное. Будущее веба.", "where": "YouTube, Google, HTTP/3", "fact": "Сделан поверх UDP, хотя ведёт себя как TCP",
          "dependsOn": ["rfc0768"], "usedBy": ["rfc9114"], "replaces": [], "replacedBy": [], "color": "#66BB6A" },
        { "id": "rfc9114", "number": 9114, "name": "HTTP/3", "fullName": "Hypertext Transfer Protocol version 3", "year": 2022, "status": "active", "layer": "application", "category": "web", "plant": "flower",
          "description": "HTTP поверх QUIC: без TCP-задержек, устойчив к потерям пакетов.", "where": "Новейшие сайты", "fact": "Не боится потерь пакетов в плохом Wi-Fi",
          "dependsOn": ["rfc9000"], "usedBy": [], "replaces": ["rfc7540"], "replacedBy": [], "color": "#EC407A" },
        { "id": "rfc1034", "number": 1034, "name": "DNS (структура)", "fullName": "Domain Names - Concepts and Facilities", "year": 1988, "status": "active", "layer": "application", "category": "naming", "plant": "flower",
          "description": "Основы работы DNS: зоны, серверы, иерархия. Концептуальная база для RFC 1035.", "where": "Устройство DNS", "fact": "Всего 13 адресов корневых серверов на весь интернет",
          "dependsOn": ["rfc0791"], "usedBy": ["rfc1035"], "replaces": [], "replacedBy": [], "color": "#18BC9C" },
        { "id": "rfc3848", "number": 3848, "name": "DHCP IPv4", "fullName": "DHCP - DHCP Option for IPv4 Link Settings", "year": 2004, "status": "active", "layer": "network", "category": "addressing", "plant": "sprout",
          "description": "Опции DHCP для IPv4: раздача адресов, маршрутов и DNS-серверов.", "where": "Настройка IP, маршрутов и DNS", "fact": "Опции DHCP — маленькие «записки» роутера устройству",
          "dependsOn": ["rfc2131"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#FFAB40" },
        { "id": "rfc9106", "number": 9106, "name": "PBKDF2", "fullName": "Password-Based Cryptography Specification", "year": 2022, "status": "active", "layer": "presentation", "category": "security", "plant": "mushroom",
          "description": "Хэш-функция для паролей: защищённое хранение учёtnых данных.", "where": "Хранение паролей", "fact": "Специально медленный: сотни тысяч итераций против подбора",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#B39DDB" },
        { "id": "rfc2326", "number": 2326, "name": "RTSP", "fullName": "Real Time Streaming Protocol", "year": 1998, "status": "updated", "layer": "session", "category": "streaming", "plant": "vine",
          "description": "Протокол управления стримами: play, pause, stop для видео и аудио в реальном времени.", "where": "Камеры видеонаблюдения", "fact": "Кнопки play/pause для сетевого видео",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#81D4FA" },
        { "id": "rfc3986", "number": 3986, "name": "URI", "fullName": "Uniform Resource Identifier", "year": 2005, "status": "active", "layer": "application", "category": "naming", "plant": "sprout",
          "description": "Стандарт формата адресов: как писать ссылки, чтобы все понимали.", "where": "Каждая ссылка", "fact": "Схема :// — его рук дело",
          "dependsOn": [], "usedBy": ["rfc2616"], "replaces": ["rfc1738"], "replacedBy": [], "color": "#FF7043" },
        { "id": "rfc6265", "number": 6265, "name": "HTTP Cookies", "fullName": "HTTP State Management Mechanism", "year": 2011, "status": "active", "layer": "application", "category": "web", "plant": "mushroom",
          "description": "Cookie — как сайты помнят вас между запросами.", "where": "Корзины, «вы вошли как…»", "fact": "Придуманы в Netscape в 1994 году",
          "dependsOn": ["rfc2616"], "usedBy": [], "replaces": ["rfc2965"], "replacedBy": [], "color": "#BCAAA4" },
        { "id": "rfc4566", "number": 4566, "name": "SDP", "fullName": "SDP: Session Description Protocol", "year": 2006, "status": "active", "layer": "session", "category": "streaming", "plant": "flower",
          "description": "Формат описания сессий: кодеки, адреса, порты для VoIP и видеоконференций.", "where": "Zoom и звонки", "fact": "Два клиента договариваются о кодеках обычным текстом",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#CE93D8" },
        { "id": "rfc5766", "number": 5766, "name": "ICE", "fullName": "Traversal Using Relays around NAT", "year": 2010, "status": "active", "layer": "application", "category": "networking", "plant": "mushroom",
          "description": "NAT-traversal для WebRTC: находит путь даже через роутеры и файрволы.", "where": "Видеозвонки через роутеры", "fact": "Пробивает NAT: находит путь, даже если оба за файрволом",
          "dependsOn": ["rfc0768"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#AED581" },
        { "id": "rfc1157", "number": 1157, "name": "SNMP", "fullName": "Simple Network Management Protocol", "year": 1990, "status": "active", "layer": "application", "category": "monitoring", "plant": "mushroom",
          "description": "Наблюдение за сетью: роутеры сами докладывают о нагрузке и поломках.", "where": "Мониторинг сетей, Zabbix", "fact": "Роутер сам присылает «тревогу» админу",
          "dependsOn": ["rfc0768"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#7E57C2" },
        { "id": "rfc0854", "number": 854, "name": "Telnet", "fullName": "Telnet Protocol", "year": 1983, "status": "legacy", "layer": "application", "category": "remote", "plant": "vine",
          "description": "Древнее удалённое управление: печатаешь команды на чужой машине.", "where": "Музей, старые железки", "fact": "Пароль летит открытым текстом — его убил SSH",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#78909C" },
        { "id": "rfc1122", "number": 1122, "name": "Host Req.", "fullName": "Requirements for Internet Hosts", "year": 1989, "status": "active", "layer": "network", "category": "core", "plant": "tree",
          "description": "Конституция интернета: что обязан уметь каждый компьютер в сети.", "where": "Учебники по сетям", "fact": "Больше тысячи страниц требований",
          "dependsOn": [], "usedBy": ["rfc0791","rfc0793"], "replaces": [], "replacedBy": [], "color": "#26A69A" },
        { "id": "rfc1436", "number": 1436, "name": "Gopher", "fullName": "Gopher Protocol", "year": 1993, "status": "legacy", "layer": "application", "category": "web", "plant": "flower",
          "description": "Интернет до веба: меню из текстовых документов вместо сайтов.", "where": "История интернета", "fact": "Проиграл HTTP из-за платной лицензии",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#A1887F" },
        { "id": "rfc1738", "number": 1738, "name": "URL", "fullName": "Uniform Resource Locators", "year": 1994, "status": "legacy", "layer": "application", "category": "naming", "plant": "sprout",
          "description": "Первый формат адресов: как писать ссылки, чтобы все понимали.", "where": "Старые ссылки", "fact": "Его заменил более общий URI",
          "dependsOn": [], "usedBy": ["rfc2616"], "replaces": [], "replacedBy": ["rfc3986"], "color": "#FFC107" },
        { "id": "rfc1918", "number": 1918, "name": "PrivAddr", "fullName": "Private Address Space", "year": 1996, "status": "active", "layer": "network", "category": "addressing", "plant": "tree",
          "description": "Домашние адреса: 192.168.x.x, которые нельзя маршрутизировать в интернет.", "where": "192.168.x.x дома и в офисе", "fact": "Три диапазона: 10/8, 172.16/12, 192.168/16 — выучи их",
          "dependsOn": ["rfc0791"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#7CB342" },
        { "id": "rfc1945", "number": 1945, "name": "HTTP/1.0", "fullName": "Hypertext Transfer Protocol 1.0", "year": 1996, "status": "legacy", "layer": "application", "category": "web", "plant": "flower",
          "description": "Первый веб-протокол: один запрос — одно соединение, медленно, но работало.", "where": "Первые сайты", "fact": "Каждый запрос открывал новое соединение",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": ["rfc2616"], "color": "#FFB300" },
        { "id": "rfc2617", "number": 2617, "name": "HTTP Auth", "fullName": "HTTP Authentication", "year": 1999, "status": "updated", "layer": "application", "category": "auth", "plant": "flower",
          "description": "Окна «введите логин и пароль»: как сайт проверяет, кто ты.", "where": "Окна входа на сайтах", "fact": "Схема Basic кодирует пароль в base64 — это НЕ шифрование",
          "dependsOn": ["rfc2616"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#00897B" },
        { "id": "rfc2818", "number": 2818, "name": "HTTPS", "fullName": "HTTP Over TLS", "year": 2000, "status": "active", "layer": "application", "category": "security", "plant": "flower",
          "description": "Обычный HTTP внутри TLS-туннеля: замок в адресной строке.", "where": "Замок в браузере", "fact": "Просто HTTP + шифрование — а разница огромна",
          "dependsOn": ["rfc2616","rfc5246"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#F06292" },
        { "id": "rfc3261", "number": 3261, "name": "SIP", "fullName": "Session Initiation Protocol", "year": 2002, "status": "active", "layer": "session", "category": "voice", "plant": "flower",
          "description": "IP-телефония: устанавливает звонки, как HTTP открывает страницы.", "where": "Офисные АТС, звонки", "fact": "Похож на HTTP: INVITE вместо GET",
          "dependsOn": ["rfc0768"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#BA68C8" },
        { "id": "rfc3550", "number": 3550, "name": "RTP", "fullName": "Real-time Transport Protocol", "year": 2003, "status": "active", "layer": "application", "category": "streaming", "plant": "vine",
          "description": "Голос и видео в звонках: лучше потерять кадр, чем зависнуть.", "where": "Звонки, стримы", "fact": "Не гарантирует доставку — специально",
          "dependsOn": ["rfc0768"], "usedBy": ["rfc3711"], "replaces": [], "replacedBy": [], "color": "#4FC3F7" },
        { "id": "rfc3711", "number": 3711, "name": "SRTP", "fullName": "Secure RTP", "year": 2004, "status": "active", "layer": "application", "category": "security", "plant": "vine",
          "description": "Тот же RTP, но зашифрованный: конфиденциальные звонки.", "where": "Защищённые звонки", "fact": "RTP + шифрование без потери скорости",
          "dependsOn": ["rfc3550"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#7986CB" },
        { "id": "rfc3977", "number": 3977, "name": "NNTP", "fullName": "Network News Transfer Protocol", "year": 2006, "status": "active", "layer": "application", "category": "news", "plant": "mushroom",
          "description": "Группы новостей Usenet: предок форумов и Reddit.", "where": "Usenet, история форумов", "fact": "Дискуссии в интернете начались здесь — с 1986 года",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#9E9E9E" },
        { "id": "rfc4511", "number": 4511, "name": "LDAP", "fullName": "Lightweight Directory Access Protocol", "year": 2006, "status": "active", "layer": "application", "category": "auth", "plant": "mushroom",
          "description": "Корпоративный справочник: один логин на почту, Wi-Fi и принтер.", "where": "Офисные сети, Active Directory", "fact": "Телефонная книга всей компании",
          "dependsOn": ["rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#5C6BC0" },
        { "id": "rfc4960", "number": 4960, "name": "SCTP", "fullName": "Stream Control Transmission Protocol", "year": 2007, "status": "active", "layer": "transport", "category": "transport", "plant": "vine",
          "description": "Гибрид TCP и UDP: надёжно, но сообщениями, а не потоком.", "where": "Сигнализация 4G/5G", "fact": "Телефонные сети держатся на нём",
          "dependsOn": ["rfc0791"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#00838F" },
        { "id": "rfc5246", "number": 5246, "name": "TLS 1.2", "fullName": "Transport Layer Security 1.2", "year": 2008, "status": "updated", "layer": "presentation", "category": "security", "plant": "tree",
          "description": "Шифрование эпохи 2010-х: замок интернета до версии 1.3.", "where": "HTTPS до 2018 года", "fact": "Устарел из-за слабых шифров — нужен 1.3",
          "dependsOn": ["rfc0793"], "usedBy": ["rfc2818"], "replaces": [], "replacedBy": ["rfc8446"], "color": "#4DB6AC" },
        { "id": "rfc5322", "number": 5322, "name": "EmailFmt", "fullName": "Internet Message Format", "year": 2008, "status": "active", "layer": "application", "category": "email", "plant": "flower",
          "description": "Устройство письма: тема, от, кому — формат не менялся десятилетиями.", "where": "Каждое письмо", "fact": "Шапка письма читается человеком без программ",
          "dependsOn": [], "usedBy": ["rfc5321"], "replaces": [], "replacedBy": [], "color": "#F48FB1" },
        { "id": "rfc6749", "number": 6749, "name": "OAuth 2.0", "fullName": "OAuth 2.0 Authorization Framework", "year": 2012, "status": "active", "layer": "session", "category": "auth", "plant": "flower",
          "description": "Кнопки «войти через Google»: сайт не видит твой пароль — только токен.", "where": "Вход через соцсети", "fact": "Пароль остаётся у Google, сайт получает токен",
          "dependsOn": ["rfc2616"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#FF8A65" },
        { "id": "rfc7252", "number": 7252, "name": "CoAP", "fullName": "Constrained Application Protocol", "year": 2014, "status": "active", "layer": "application", "category": "iot", "plant": "sprout",
          "description": "HTTP для лампочек: тот же REST, но лёгкий и поверх UDP.", "where": "Умный дом, датчики", "fact": "Работает на батарейке годами",
          "dependsOn": ["rfc0768"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#9CCC65" },
        { "id": "rfc7519", "number": 7519, "name": "JWT", "fullName": "JSON Web Token", "year": 2015, "status": "active", "layer": "session", "category": "auth", "plant": "sprout",
          "description": "Токены входа: три части через точку, подпись защищает от подделки.", "where": "Токены на сайтах", "fact": "Payload читается всеми — не клади туда секреты",
          "dependsOn": [], "usedBy": ["rfc6749"], "replaces": [], "replacedBy": [], "color": "#FFE082" },
        { "id": "rfc8484", "number": 8484, "name": "DoH", "fullName": "DNS over HTTPS", "year": 2018, "status": "active", "layer": "application", "category": "security", "plant": "flower",
          "description": "Приватный DNS внутри HTTPS: провайдер не видит твои запросы.", "where": "Приватность в браузере", "fact": "DNS-запросы маскируются под обычный веб-трафик",
          "dependsOn": ["rfc2616","rfc1035"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#00ACC1" },
            { "id": "hw-router", "name": "Router", "fullName": "Маршрутизатор", "year": 1984, "status": "active", "layer": "network", "category": "networking", "plant": "mushroom",
          "description": "Коробка, которая решает, куда отправить пакет дальше. Домашний роутер раздаёт Wi-Fi и прячет сеть за NAT.", "where": "Домашний Wi-Fi, провайдеры", "fact": "Домашний роутер — это маленький компьютер, часто с Linux внутри",
          "dependsOn": ["rfc0791"], "usedBy": ["rfc4271"], "replaces": [], "replacedBy": [], "color": "#607D8B", "url": "https://en.wikipedia.org/wiki/Router_(computing)" },
        { "id": "hw-switch", "name": "Switch", "fullName": "Коммутатор", "year": 1990, "status": "active", "layer": "link", "category": "networking", "plant": "mushroom",
          "description": "Учит MAC-адреса и шлёт кадры только в нужный порт: тихо и быстро.", "where": "Офисные сети", "fact": "Первый EtherSwitch 1990 года отправил хабы в музей",
          "dependsOn": ["rfc0826"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#78909C", "url": "https://en.wikipedia.org/wiki/Network_switch" },
        { "id": "hw-firewall", "name": "Firewall", "fullName": "Межсетевой экран", "year": 1988, "status": "active", "layer": "network", "category": "security", "plant": "mushroom",
          "description": "Страж на границе сети: режет лишние соединения по правилам.", "where": "Офисы, серверы", "fact": "Первые экраны появились в конце 80-х в DEC",
          "dependsOn": ["rfc0791", "rfc0793"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#EF5350", "url": "https://en.wikipedia.org/wiki/Firewall_(computing)" },
        { "id": "hw-wifi", "name": "Wi-Fi точка", "fullName": "Wireless Access Point", "year": 1999, "status": "active", "layer": "physical", "category": "networking", "plant": "mushroom",
          "description": "Мост между воздухом и проводами: раздаёт интернет по радиоканалу.", "where": "Кафе, дом, офис", "fact": "Стандарт 802.11b 1999 года дал 11 Мбит/с",
          "dependsOn": ["rfc0791"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#29B6F6", "url": "https://en.wikipedia.org/wiki/Wireless_access_point" },
        { "id": "hw-modem", "name": "Modem", "fullName": "Модем", "year": 1958, "status": "active", "layer": "physical", "category": "networking", "plant": "mushroom",
          "description": "Переводчик цифры в гудки и обратно: так интернет приходил по телефонной линии.", "where": "Dial-up, DSL, оптика", "fact": "Bell 101 1958 года жал 110 бит/с",
          "dependsOn": [], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#8D6E63", "url": "https://en.wikipedia.org/wiki/Modem" },
        { "id": "hw-lb", "name": "Балансировщик", "fullName": "Load Balancer", "year": 1996, "status": "active", "layer": "network", "category": "networking", "plant": "mushroom",
          "description": "Раздаёт запросы по серверам, чтобы ни один не лёг под нагрузкой.", "where": "Дата-центры, облака", "fact": "F5, основанная в 1996, сделала балансировку бизнесом",
          "dependsOn": ["rfc0793", "rfc2616"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#26A69A", "url": "https://en.wikipedia.org/wiki/Load_balancing_(computing)" },
        { "id": "os-unix", "name": "UNIX", "fullName": "UNIX", "year": 1969, "status": "active", "layer": "network", "category": "os", "plant": "tree",
          "description": "Прародитель: отсюда пайпы, сокеты и идея «всё — файл».", "where": "Серверы, история", "fact": "Первую версию Кен Томпсон написал за месяц",
          "dependsOn": [], "usedBy": ["os-linux", "os-macos"], "replaces": [], "replacedBy": [], "color": "#9E9E9E", "url": "https://en.wikipedia.org/wiki/Unix" },
        { "id": "os-linux", "name": "Linux", "fullName": "Linux", "year": 1991, "status": "active", "layer": "network", "category": "os", "plant": "tree",
          "description": "Свободное ядро: от роутеров и Android до суперкомпьютеров.", "where": "Серверы, Android, роутеры", "fact": "Торвальдс писал его как хобби — «не большое и профессиональное»",
          "dependsOn": ["os-unix"], "usedBy": ["os-android", "virt-docker", "virt-hypervisor"], "replaces": [], "replacedBy": [], "color": "#FFC107", "url": "https://en.wikipedia.org/wiki/Linux" },
        { "id": "os-windows", "name": "Windows", "fullName": "Microsoft Windows", "year": 1985, "status": "active", "layer": "network", "category": "os", "plant": "tree",
          "description": "Система девяти из десяти домашних ПК: окна, драйверы и совместимость десятилетиями.", "where": "Домашние ПК, офисы", "fact": "Windows 1.0 1985 года была надстройкой над MS-DOS",
          "dependsOn": [], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#00ADEF", "url": "https://en.wikipedia.org/wiki/Microsoft_Windows" },
        { "id": "os-macos", "name": "macOS", "fullName": "macOS", "year": 2001, "status": "active", "layer": "network", "category": "os", "plant": "tree",
          "description": "UNIX с человеческим лицом: Darwin внутри, дизайн снаружи.", "where": "Ноутбуки разработчиков", "fact": "Ядро Darwin — потомок BSD, родственника UNIX",
          "dependsOn": ["os-unix"], "usedBy": ["os-ios"], "replaces": [], "replacedBy": [], "color": "#B0BEC5", "url": "https://en.wikipedia.org/wiki/MacOS" },
        { "id": "os-android", "name": "Android", "fullName": "Android", "year": 2008, "status": "active", "layer": "network", "category": "os", "plant": "tree",
          "description": "Linux в кармане: самая популярная ОС планеты.", "where": "Смартфоны", "fact": "Первый HTC Dream вышел в 2008 году",
          "dependsOn": ["os-linux"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#3DDC84", "url": "https://en.wikipedia.org/wiki/Android_(operating_system)" },
        { "id": "os-ios", "name": "iOS", "fullName": "iOS", "year": 2007, "status": "active", "layer": "network", "category": "os", "plant": "tree",
          "description": "Система iPhone: строгие правила и плавные анимации.", "where": "iPhone, iPad", "fact": "Первый iPhone показали в 2007 году",
          "dependsOn": ["os-macos"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#E0E0E0", "url": "https://en.wikipedia.org/wiki/IOS" },
        { "id": "virt-hypervisor", "name": "Гипервизор", "fullName": "Hypervisor", "year": 1967, "status": "active", "layer": "application", "category": "virt", "plant": "mushroom",
          "description": "Компьютер внутри компьютера: режет железо на изолированные куски.", "where": "Дата-центры, облака", "fact": "Первый гипервизор CP-40 заработал в 1967 году",
          "dependsOn": [], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#BA68C8", "url": "https://en.wikipedia.org/wiki/Hypervisor" },
        { "id": "virt-docker", "name": "Docker", "fullName": "Docker", "year": 2013, "status": "active", "layer": "application", "category": "virt", "plant": "mushroom",
          "description": "Контейнеры: приложение едет с зависимостями и работает везде одинаково.", "where": "Разработка, деплой", "fact": "Написан на Go — языке из этого же сада",
          "dependsOn": ["os-linux", "lang-go"], "usedBy": ["virt-k8s"], "replaces": [], "replacedBy": [], "color": "#2496ED", "url": "https://en.wikipedia.org/wiki/Docker_(software)" },
        { "id": "virt-k8s", "name": "Kubernetes", "fullName": "Kubernetes", "year": 2014, "status": "active", "layer": "application", "category": "virt", "plant": "mushroom",
          "description": "Дирижёр контейнеров: перезапускает упавшее и масштабирует под нагрузку.", "where": "Облака, микросервисы", "fact": "Вырос из внутренней системы Google Borg",
          "dependsOn": ["virt-docker", "lang-go"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#326CE5", "url": "https://en.wikipedia.org/wiki/Kubernetes" },
        { "id": "lang-c", "name": "C", "fullName": "C Programming Language", "year": 1972, "status": "active", "layer": "application", "category": "lang", "plant": "flower",
          "description": "Мать системных языков: на нём UNIX, Linux и половина сада.", "where": "Ядра ОС, драйверы, встраиваемое", "fact": "Создан, чтобы переписать UNIX с ассемблера",
          "dependsOn": [], "usedBy": ["os-unix", "os-linux", "lang-python", "lang-go"], "replaces": [], "replacedBy": [], "color": "#5C6BC0", "url": "https://en.wikipedia.org/wiki/C_(programming_language)" },
        { "id": "lang-python", "name": "Python", "fullName": "Python", "year": 1991, "status": "active", "layer": "application", "category": "lang", "plant": "flower",
          "description": "Читается почти как английский: нейросети, скрипты и бэкенды.", "where": "ML, скрипты, веб", "fact": "Назван в честь «Монти Пайтона», а не змеи",
          "dependsOn": ["lang-c"], "usedBy": ["ai-neural"], "replaces": [], "replacedBy": [], "color": "#3776AB", "url": "https://en.wikipedia.org/wiki/Python_(programming_language)" },
        { "id": "lang-js", "name": "JavaScript", "fullName": "JavaScript", "year": 1995, "status": "active", "layer": "application", "category": "lang", "plant": "flower",
          "description": "Язык браузера: оживляет страницы, а с Node.js — и серверы.", "where": "Каждый сайт", "fact": "Создан за 10 дней в 1995 году",
          "dependsOn": [], "usedBy": ["rfc6455"], "replaces": [], "replacedBy": [], "color": "#F7DF1E", "url": "https://en.wikipedia.org/wiki/JavaScript" },
        { "id": "lang-go", "name": "Go", "fullName": "Go", "year": 2009, "status": "active", "layer": "application", "category": "lang", "plant": "flower",
          "description": "Простой как C, с потоками из коробки: язык Docker и Kubernetes.", "where": "Облака, DevOps", "fact": "Придуман в Google как ответ медленной сборке C++",
          "dependsOn": ["lang-c"], "usedBy": ["virt-docker", "virt-k8s"], "replaces": [], "replacedBy": [], "color": "#00ADD8", "url": "https://en.wikipedia.org/wiki/Go_(programming_language)" },
        { "id": "lang-rust", "name": "Rust", "fullName": "Rust", "year": 2010, "status": "active", "layer": "application", "category": "lang", "plant": "flower",
          "description": "Скорость C без падений: компилятор не даёт выстрелить в ногу.", "where": "Браузеры, драйверы, блокчейн", "fact": "Самый любимый язык по опросам Stack Overflow",
          "dependsOn": ["lang-c"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#DEA584", "url": "https://en.wikipedia.org/wiki/Rust_(programming_language)" },
        { "id": "ai-neural", "name": "Нейросети", "fullName": "Deep Neural Networks", "year": 2012, "status": "active", "layer": "application", "category": "ai", "plant": "flower",
          "description": "Слои искусственных нейронов, которые учатся на примерах: от кошек на фото до речи.", "where": "Распознавание, рекомендации", "fact": "Прорыв 2012 года начался с победы AlexNet",
          "dependsOn": ["lang-python"], "usedBy": ["ai-llm"], "replaces": [], "replacedBy": [], "color": "#AB47BC", "url": "https://en.wikipedia.org/wiki/Deep_learning" },
        { "id": "ai-llm", "name": "LLM", "fullName": "Large Language Models", "year": 2017, "status": "active", "layer": "application", "category": "ai", "plant": "flower",
          "description": "Гигантские модели, предсказывающие следующее слово: чат-боты и ассистенты.", "where": "Чат-боты, ассистенты", "fact": "Архитектура «Трансформер» описана в 2017 году",
          "dependsOn": ["ai-neural"], "usedBy": [], "replaces": [], "replacedBy": [], "color": "#7E57C2", "url": "https://en.wikipedia.org/wiki/Large_language_model" },
    ]
};